//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightClaw.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShaderModel5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShaderModel5() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightClaw.Resources.ShaderModel5", typeof(ShaderModel5).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die float4 VS(float4 position : POSITION) : SV_POSITION
        ///{
        ///    return position;
        ///}
        ///
        ///float4 PS(float4 position : SV_POSITION) : SV_Target
        ///{
        ///    return float4(1.0f, 1.0f, 0.0f, 1.0f);
        ///} ähnelt.
        /// </summary>
        public static String BasicShader {
            get {
                return ResourceManager.GetString("BasicShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die struct VS_INPUT
        ///{
        ///	float4 Position : POSITION;
        ///	float4 Color : COLOR;
        ///};
        ///
        ///struct PS_INPUT
        ///{
        ///	float4 Position : SV_POSITION;
        ///	float4 Color : COLOR;
        ///};
        ///
        ///PS_INPUT VS(VS_INPUT input)
        ///{
        ///    PS_INPUT output = (PS_INPUT)0;
        ///
        ///	output.Position = input.Position;
        ///	output.Color = input.Position;
        ///	
        ///	return output;
        ///}
        ///
        ///float4 PS(PS_INPUT input) : SV_TARGET
        ///{
        ///	return input.Color;
        ///} ähnelt.
        /// </summary>
        public static String ColoredShader {
            get {
                return ResourceManager.GetString("ColoredShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ds_5_0 ähnelt.
        /// </summary>
        public static String DomainShaderProfile {
            get {
                return ResourceManager.GetString("DomainShaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gs_5_0 ähnelt.
        /// </summary>
        public static String GeometryShaderProfile {
            get {
                return ResourceManager.GetString("GeometryShaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hs_5_0 ähnelt.
        /// </summary>
        public static String HullShaderProfile {
            get {
                return ResourceManager.GetString("HullShaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ps_5_0 ähnelt.
        /// </summary>
        public static String PixelShaderProfile {
            get {
                return ResourceManager.GetString("PixelShaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vs_5_0 ähnelt.
        /// </summary>
        public static String VertexShaderProfile {
            get {
                return ResourceManager.GetString("VertexShaderProfile", resourceCulture);
            }
        }
    }
}
